### ISSUE TITLE
Water and Lava blocks never flow?

### ISSUE THREAD

**Issue by vanjam75** [popkechupki/FireLiquidRestriction#1]
Great plugin! However, it looks like flow is always disabled:
https://github.com/popkechupki/FireLiquidRestriction/blob/debf939b84727f723e6587b465801f64e860e113/src/main/java/net/comorevi/np/flr/FireLiquidRestriction.java#L149

Line 149 seems to imply that flow if disabled if the source is a lava block or water block - regardless of the values for config.getBoolean("RestrictLava") and config.getBoolean("RestrictWater")

**Comment by popkechupki** [comment]
Ah...You are right. Thank you. I'll fix it.
